services:
  clientemqtt:
    build: ./clienteMqtt
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - MQTT_SERVER=${MQTT_SERVER}
      - TOPIC_SUBSCRIBE_1=${TOPIC_SUBSCRIBE_1}
      - TOPIC_SUBSCRIBE_2=${TOPIC_SUBSCRIBE_2}
      - TOPIC_PUBLISH=${TOPIC_PUBLISH}
    restart: unless-stopped