version: "3"
services:
  clientemqtt:
    build:
      context: ./clienteMqtt
      dockerfile: Dockerfile
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - MQTT_SERVER=${SERVIDOR}
      - TOPIC_SUBSCRIBE_1=${TOPICSUB1}
      - TOPIC_SUBSCRIBE_2=${TOPICSUB2}
      - TOPIC_PUBLISH=${TOPICPUB}
    restart: unless-stopped